version: "3.4"
services:
  feedless:
    build: .
    restart: always
    network_mode: host
    env_file: .env
    volumes:
      - feedless_ssb:/root/.ssb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$PORT/metrics"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 20s

volumes:
  feedless_ssb:
